= Text Managment
:neo4j-version: 2.3.0
:author: Håkan Persson

'''
[[introduction]]
== Introduction
To get overview of Text and icon content for artwork production

'''
[[model]]
== Model
Graphdatabase with following Node classifications:

Activity (SA2080 Rainbow)
Material (3456701, Bag, Mondi)
Article		(8112-02 Nana, Ultra, Normal wing, English, 14pcs x 10, UK)
Recepie		(variant for keeping track of updates)
Master Set	(grouping of articles for managing master text input, Normal Wing, Super Wing, Normal wing Deo)
Master		(Master text)
Translation	(Local translation of master text)
Order data	(planned artwork approval, Prepress, Artwork agency, Notes)
PCON		(Linedrawing, Supplier, pack type)


'''
[[setup]]
== Setup

//hide
//setup
[source, cypher]
----
CREATE	(PR1:Activity {Number:'SA2880 SWAT', Description:'SWAT'}),
	(PR2:Activity {Number:'SA3012 Rainbow', Description:'Rainbow'})

CREATE	(Ma:Material {Number:'3212400', Material_type:'Bag Li Rainb'}),
	(Mb:Material {Number:'3654300', Material_type:'Bag Nana Rainb'}),
	(Mc:Material {Number:'3467200', Material_type:'Bag Li SWAT'})

CREATE	(Ra:Recepie {Number:'1000005654.001', name:'Recepie 8821-12.001'}),
	(Rb:Recepie {Number:'1000005654.002', name:'Recepie 8821-12.002'}),
	(Rc:Recepie {Number:'1000006847.001', name:'Recepie 9426-12.001'})

CREATE	(Ma)-[:Is_included_in]->(Ra),
	(Mc)-[:Is_included_in]->(Rb),
	(Mb)-[:Is_included_in]->(Rc)
	
CREATE  (Aa:Article {Number:'8821-12', Brand:'Libresse', Size:'Normal Wing', Pack_count:'14'}),
	(Ac:Article {Number:'9426-12', Brand:'Nana', Size:'Normal Wing', Pack_count:'14'})
	
CREATE	(Aa)-[:Is_included_in]->(PR2),
	(Ac)-[:Is_included_in]->(PR2)

CREATE	(Ra)<-[:Is_included_in]-(Aa),
	(Rb)<-[:Is_included_in]-(Aa),
	(Rc)<-[:Is_included_in]-(Ac)
	
CREATE	(MT1:Master {Position:'Bulletpoint 1', master_text:'Shaped front and back to fit your curves'}),
	(MT2:Master {Position:'Bulletpoint 2', master_text:'All-around barrier'}),
	(MT3:Master {Position:'ICON 032', master_text:'Dont flush icon'}),
	(MT4:Master {Position:'Bulletpoint 2', master_text:'Now enven better SWAT'}),
	(MT5:Master {Position:'Address', master_text:'Consumer Contact address'})

CREATE	(TT1:onpack {Position:'Bulletpoint 1', Translated_text:'translation 76sdhksb shfjh', Language:'FR'}),
	(TT2:onpack {Position:'Bulletpoint 2', Translated_text:'translation sdfj sfdh jh s', Language:'FR'}),
	(TT3:onpack {Position:'Bulletpoint 1', Translated_text:'translation sfh jhsjhj hjsf', Language:'UK'}),
	(TT4:onpack {Position:'Bulletpoint 2', Translated_text:'translation dsfsf fsf fss', Language:'UK'}),
	(TT5:onpack {Position:'Bulletpoint 2', Translated_text:'translation swat', Language:'UK'}),
	(TT6:onpack {Position:'Address', Translated_text:'UK contact dsjdsj', Language:'UK'}),
	(TT7:onpack {Position:'Address', Translated_text:'UK contact dsjdsj', Language:'FR'})
	
CREATE	(TT1)-[:translation_of]->(MT1),
	(TT2)-[:translation_of]->(MT2),
	(TT3)-[:translation_of]->(MT1),
	(TT4)-[:translation_of]->(MT2),
	(TT5)-[:translation_of]->(MT4),
	(TT6)-[:translation_of]->(MT5),
	(TT7)-[:translation_of]->(MT5)
	
CREATE 	(MT3)-[:Is_used_in]->(Ma),
	(MT3)-[:Is_used_in]->(Mb),
	(MT3)-[:Is_used_in]->(Mc)

CREATE	(MS1:Master_set {Design_Name:'Rainbow NW', Product_Size:'Normal Wing'}),
	(MS2:Master_set {Design_Name:'SWAT NW', Product_Size:'Normal Wing'})

CREATE	(Aa)-[:Is_included_in]->(MS1),
	(Aa)-[:Is_included_in]->(MS1),
	(Ac)-[:Is_included_in]->(MS1),
	(Aa)-[:Is_included_in]->(MS2)

CREATE	(MS1)-[:Is_included_in]->(Ma),
	(MS1)-[:Is_included_in]->(Mb),
	(MS2)-[:Is_included_in]->(Mc)
	
CREATE	(MS1)-[:Is_included_in]->(MT1),
	(MS1)-[:Is_included_in]->(MT2),
	(MS1)-[:Is_included_in]->(MT3),
	(MS2)-[:Is_included_in]->(MT4)

CREATE	(TT1)-[:Content_for]->(Mb),
	(TT2)-[:Content_for]->(Mb),
	(TT3)-[:Content_for]->(Ma),
	(TT4)-[:Content_for]->(Ma),
	(TT5)-[:Content_for]->(Mc),
	(TT6)-[:Content_for]->(Ma),
	(TT7)-[:Content_for]->(Mb)
	
CREATE	(Oa:Order_data {Planned_Approval_date:'2016-08-12', Artwork_Agency:'Collabra'}),
	(Ob:Order_data {Planned_Approval_date:'2016-08-12', Artwork_Agency:'Collabra'}),
	(Oc:Order_data {Planned_Approval_date:'2016-08-12', Artwork_Agency:'Collabra'})
	
CREATE	(Ma)-[:has]->(Oa),
	(Mb)-[:has]->(Ob),
	(Mc)-[:has]->(Oc)

CREATE	(PCON1:PCON {Number:'10000078787', Product_Size:'Normal Wing', Adim:'190', Bdim:'120', Cdim:'32'})
	
CREATE	(PCON1)-[:Drawing_used_for]->(Ma),
	(PCON1)-[:Drawing_used_for]->(Mb),
	(PCON1)-[:Drawing_used_for]->(Mc)

----

//graph
...
[[Wanted end result]]
=== Wanted end result
List of text and icon objects that shuld be included in artwork.
Order data, who is artwork agency, who is prepress, timings.
PCON Linedrawing to be used
PCON Supplier
Material no
[source, cypher]
----
MATCH (n:Activity)--(a:Article)--(r:Recepie)--(m:Material {Number:'3212400'})--(tt:onpack)
MATCH (m)--(ms:Master)
MATCH (m)--(PCON:PCON)
RETURN n,a,r,m,tt,ms,PCON
----
//graph_result
...
[[Activity Initsiation]]
=== Activity initsiation
Input from PLM ats Assignment approved, we know assortment and material specs change scope
[source, cypher]
----
MATCH (n:Activity)--(a:Article)--(r:Recepie)--(m:Material)--(PCON:PCON)
RETURN n,a,r,m,PCON
----
//graph_result

=== GDM requests address update.
exsisting Address text objects are linked to the new articles/artworks??, following sold in list.
Market can keep exsisting or create new version.
Market can take away link and use another approved address text object.

=== GDM initsiate Leagal icons
GDM links icons to artworks, for review at markets.
We use label classification guide + present setup

=== Local market contacts
List of who is text translator, who is artwork approver at local market.
Local market or reginal manager shuld update.

=== GDM Adds Master text classifications and master text request.
Master classification / grouping can be for Normal / Super / Normal deo etc..
Master text object / request is added to each classification. GHC to update.
If master text has been send out for translation, then new master text version is needed for further updates.
If same Master text is used in two classification, same object is linked to both.
FIX!! add Rainbow SW
FIX!! promo artiklar, såsom "economy" master text object läggs upp direkt mot artikeln, ej mot classification.
FIX!! visa lista som GHC får - artiklar Classification, extra texter som är direkt mot artikel.
FIX!! icon guide, checklist - icon 032 - Bags, RU
[source, cypher]
----
MATCH (n:Activity)--(a:Article)--(ms:Master_set)--(mt:Master)
RETURN n,a,ms,mt
----
//graph_result

=== GDM Initsiates Local translations
When Master text is approved, 
gdm sends out request for translation dependent on Basket input.
Translation objects are added to master text object.
Translation object is linked directly to all artworks that is linked to master classification.
If a translated text has been used in a artwork revision, then next changes creates a new text revision.
FIX!! Special promotion texts can be requested directly towards an artwork, without using classification
FIX!! Icons syns ej i match så kan any användas eller hur det var.


[source, cypher]
----
MATCH (n:Activity {Number:'SA3012 Rainbow'})--(a:Article)--(ms:Master_set)--(mt:Master)--(tt:onpack)
RETURN a,ms,mt,tt
----
//graph_result
...
=== GDM Links translations to artwork
Translation object is linked directly to artwork.
FIX!!! icons

[source, cypher]
----
MATCH (n:Activity {Number:'SA3012 Rainbow'})--(a:Article)--(ms:Master_set)--(mt:Master)--(tt:onpack)--(m:Material)
RETURN ms,mt,tt,m
----
//graph_result
'''

